// Scripted WhatsApp conversations for the WhatsApp Discovery page.
// Each message: { from: 'user' | 'bot', text, buttons?, file?, card?, system? }
// `system` is the index in `systems` that this message completes (lights up the backend panel).

export const WHATSAPP_FLOWS = [
  {
    id: 'onboarding',
    title: 'Employee onboarding',
    icon: 'fa-user-plus',
    summary: 'A new joiner shares details and documents on WhatsApp; the bot creates every account automatically.',
    persona: 'Aarav Sharma · new joiner',
    systems: [
      { icon: 'fa-brands fa-whatsapp', label: 'WhatsApp bot', note: 'Collects details & documents' },
      { icon: 'fa-solid fa-ticket', label: 'ServiceNow', note: 'Onboarding request REQ0010421' },
      { icon: 'fa-solid fa-robot', label: 'Active Directory (T4)', note: 'Domain user & role' },
      { icon: 'fa-brands fa-microsoft', label: 'Microsoft 365', note: 'Mailbox & Teams' },
      { icon: 'fa-solid fa-user-check', label: 'OrangeHRM', note: 'Employee profile' },
    ],
    messages: [
      { from: 'user', text: 'Hi' },
      { from: 'bot', text: 'Hello! I am the AutomationEdge HR assistant. How can I help you today?', buttons: ['Onboarding', 'Leave', 'Salary slip', 'Resignation'] },
      { from: 'user', text: 'Onboarding' },
      { from: 'bot', text: 'Welcome aboard! Please share your full legal name and personal email.' },
      { from: 'user', text: 'Aarav Sharma, aarav.sharma@example.com' },
      { from: 'bot', text: 'Thanks Aarav. Now upload your Government ID (Aadhaar or Passport).' },
      { from: 'user', file: { name: 'Aadhaar_Aarav_Sharma.pdf', size: '2.4 MB' } },
      { from: 'bot', text: 'Received. Last one: your signed offer letter.' },
      { from: 'user', file: { name: 'Signed_Offer_Letter.pdf', size: '1.8 MB' }, system: 0 },
      { from: 'bot', card: { icon: 'fa-ticket', title: 'Request created', lines: ['ServiceNow REQ0010421', 'Waiting for HR approval'] }, system: 1 },
      { from: 'bot', text: 'HR has approved your onboarding. Setting up your accounts now…' },
      { from: 'bot', card: { icon: 'fa-robot', title: 'Active Directory', lines: ['User aarav.sharma created', 'Role: Engineering'] }, system: 2 },
      { from: 'bot', card: { icon: 'fa-envelope', title: 'Microsoft 365', lines: ['aarav.sharma@automationedge.ai', 'Mailbox & Teams active'] }, system: 3 },
      { from: 'bot', card: { icon: 'fa-user-check', title: 'OrangeHRM', lines: ['Employee #17 created', 'Linked to work email'] }, system: 4 },
      { from: 'bot', text: 'All set! Your laptop (MacBook Pro M3 Max) ships on 14 Oct. Welcome to the team!' },
      { from: 'user', text: 'Thank you!' },
    ],
  },
  {
    id: 'offboarding',
    title: 'Employee offboarding',
    icon: 'fa-person-walking-arrow-right',
    summary: 'An employee submits a resignation; access is revoked and the relieving letter is issued without paperwork.',
    persona: 'Priya Iyer · employee',
    systems: [
      { icon: 'fa-brands fa-whatsapp', label: 'WhatsApp bot', note: 'Captures resignation' },
      { icon: 'fa-solid fa-ticket', label: 'ServiceNow', note: 'Exit request & laptop return' },
      { icon: 'fa-solid fa-robot', label: 'Active Directory (T4)', note: 'Account disabled' },
      { icon: 'fa-brands fa-microsoft', label: 'Microsoft 365', note: 'Licence removed' },
      { icon: 'fa-solid fa-file-pdf', label: 'Relieving letter', note: 'PDF emailed' },
    ],
    messages: [
      { from: 'user', text: 'Hi, I want to submit my resignation' },
      { from: 'bot', text: 'Sorry to see you go, Priya. Please confirm your last working day.', buttons: ['30 Oct 2026', 'Choose another date'] },
      { from: 'user', text: '30 Oct 2026' },
      { from: 'bot', text: 'Could you share the reason for leaving? This stays confidential.' },
      { from: 'user', text: 'Relocating to another city', system: 0 },
      { from: 'bot', card: { icon: 'fa-ticket', title: 'Exit request created', lines: ['ServiceNow REQ0010588', 'Laptop return INC0040611'] }, system: 1 },
      { from: 'bot', text: 'Your manager approved the resignation. Clearance is in progress.' },
      { from: 'bot', card: { icon: 'fa-robot', title: 'Active Directory', lines: ['Account disabled on last day', 'Group access removed'] }, system: 2 },
      { from: 'bot', card: { icon: 'fa-envelope', title: 'Microsoft 365', lines: ['Mailbox converted to shared', 'Licence released'] }, system: 3 },
      { from: 'bot', text: 'Here is your relieving letter. All the best for your next chapter!' },
      { from: 'bot', file: { name: 'Relieving_Letter_Priya_Iyer.pdf', size: '220 KB' }, system: 4 },
      { from: 'user', text: 'Thanks for everything!' },
    ],
  },
  {
    id: 'salary',
    title: 'Salary slip',
    icon: 'fa-file-invoice-dollar',
    summary: 'Employees fetch any month’s payslip on WhatsApp after a one-time verification.',
    persona: 'Rohan Mehta · employee',
    systems: [
      { icon: 'fa-brands fa-whatsapp', label: 'WhatsApp bot', note: 'Request received' },
      { icon: 'fa-solid fa-shield-halved', label: 'OTP verification', note: 'Identity confirmed' },
      { icon: 'fa-solid fa-user-check', label: 'OrangeHRM payroll', note: 'Payslip fetched' },
      { icon: 'fa-solid fa-file-pdf', label: 'Payslip PDF', note: 'Password-protected' },
    ],
    messages: [
      { from: 'user', text: 'Salary slip' },
      { from: 'bot', text: 'Sure Rohan. For your security, enter the 6-digit code sent to your registered email.', system: 0 },
      { from: 'user', text: '482913' },
      { from: 'bot', text: 'Verified. Which month do you need?', buttons: ['September 2026', 'August 2026', 'July 2026'], system: 1 },
      { from: 'user', text: 'September 2026' },
      { from: 'bot', card: { icon: 'fa-indian-rupee-sign', title: 'September 2026', lines: ['Net pay ₹2,18,450', 'Credited on 30 Sep'] }, system: 2 },
      { from: 'bot', file: { name: 'Payslip_Sep_2026_Rohan_Mehta.pdf', size: '96 KB' }, system: 3 },
      { from: 'bot', text: 'The PDF password is your PAN in capitals. Need anything else?', buttons: ['Tax summary', 'No, thanks'] },
      { from: 'user', text: 'No, thanks' },
    ],
  },
  {
    id: 'leave',
    title: 'Leave application',
    icon: 'fa-calendar-days',
    summary: 'Employees check balances and apply for leave; the manager approves right inside WhatsApp.',
    persona: 'Ananya Sen · employee',
    systems: [
      { icon: 'fa-brands fa-whatsapp', label: 'WhatsApp bot', note: 'Leave request captured' },
      { icon: 'fa-solid fa-user-check', label: 'OrangeHRM leave', note: 'Balance checked & request filed' },
      { icon: 'fa-solid fa-user-tie', label: 'Manager approval', note: 'Approved on WhatsApp' },
      { icon: 'fa-solid fa-calendar-check', label: 'Calendar', note: 'Out-of-office set' },
    ],
    messages: [
      { from: 'user', text: 'Leave' },
      { from: 'bot', card: { icon: 'fa-calendar-days', title: 'Your leave balance', lines: ['Casual 12 · Sick 8', 'Privilege 15'] } },
      { from: 'bot', text: 'Which type of leave would you like?', buttons: ['Casual', 'Sick', 'Privilege'] },
      { from: 'user', text: 'Casual' },
      { from: 'bot', text: 'Please share the dates.' },
      { from: 'user', text: '4 Nov to 5 Nov, family function', system: 0 },
      { from: 'bot', text: '2 days of casual leave (4–5 Nov) requested. Sent to your manager, Amit.', system: 1 },
      { from: 'bot', card: { icon: 'fa-user-tie', title: 'Manager approved', lines: ['Amit Deshmukh approved', 'Balance now: Casual 10'] }, system: 2 },
      { from: 'bot', text: 'Your out-of-office reply and team calendar are updated. Enjoy your break!', system: 3 },
      { from: 'user', text: 'Great, thanks!' },
    ],
  },
];
